version: "3.1"
services:
  redis6379:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server /app/redis.conf
    volumes:
      - ./redis_data/:/data/
      - ./redis.conf:/app/redis.conf

  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 9999:8080
    links:
      - 'redis6379:redis'
    depends_on:
      - redis6379




